sudo: false
dist: bionic
language: java

before_install:
  - sudo add-apt-repository ppa:linuxuprising/java -y
  - sudo apt update -q
  - sudo apt install -y oracle-java10-installer

script: mvn clean install

cache:
  directories:
  - $HOME/.m2