server:
  port: 8443
  ssl:
    enabled: true
    key-alias: marid
    key-store: classpath:marid.jks
    key-store-type: JKS
    key-password: 123456
    key-store-provider: SUN
    key-store-password: 123456
  servlet:
    session:
      cookie:
        name: sid
        http-only: true
        secure: true
logging:
  level:
    root: info
  pattern:
    dateformat: HH:mm:ss.SSS
spring:
  thymeleaf:
    enable-spring-el-compiler: true